config/routes.rb
Rem::Application.routes.draw do
  # RESTful resources
  resources :password_resets, :places, :sessions
  resources :users, :except => [:show] # Rest API
  resources :routes, :except => [:show, :edit]
  resources :relationships, :only => [:create, :destroy]
  resources :route_relationships, :only => [:create, :destroy]

  # Users, sessions and accounts
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post '/search' => 'sessions#search', as: 'search'
  get 'signup' => 'users#new', as: 'signup'
  get 'ajax_request' => 'users#ajax_request', as: 'ajax_request'
  get 'account' => 'account#edit', as: 'account'
  put 'account' => 'account#update'
  get '/places/id/:id' => 'places#edit', as: 'map_place'

  post '/ajax/update_places' => 'routes#update_places'

  post '/change_password' => 'password_resets#auth_change', as: 'auth_change'

  # Rest API: Android login
  post '/android' => 'sessions#android'

  # Rest API: Show info about users, routes and places.
  get "/users/:name" => "users#show"
  get "/routes/:name" => "routes#show"
  get "/places/:name" => "places#show"

  # Rest API: Upload/remove photos.
  post "/photos/:route_id" => "places#photos"
  delete "/photos/:place_id" => "places#delete_photos"

  # Rest API: Show the routes of the given user
  get "/users/:name/routes" => "users#routes", as: 'user_routes'

  # Rest API: Get nearby locations
  get "/places/nearby/:id" => "places#nearby"

  # Following / followers
  get '/:name/:id/followers' => 'routes#followers', as: 'followers_route'
  get '/:name/following' => "users#following", as: 'following_user'
  get '/:name/followers' => "users#followers", as: 'followers_user'

  # OAuth paths
  controller :sessions do
    scope '/auth', as: 'auth' do
      match ':provider/callback' => :create
      match :failure
    end
  end

  # Home, sweet home :)
  root to: 'home#index'

  # Footer pages
  get '/about' => "home#about"
  get '/overview' => "home#overview"
  get '/contact' => "home#contact"
  get '/help' => "home#help"

  # API page
  resources :api, :only => [:index] do
    collection do
      get 'basics' => 'api#basics'
      get 'routes_places' => 'api#routes_places'
      get 'nearby' => 'api#nearby'
    end
  end

  # This is quite ugly though
  get "/:name/:route_id" => "routes#edit", as: 'edit_route', route_id: /\d+/

  # This is the last to be routed so we don't mess things up.
  get '/:name' => "users#edit"
end

app/controllers/password_resets_controller.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == PasswordResetsController Class Definition
#
# This is the password resets controller. It handles the logic behind
# resetting passwords. It sends an email when the user wants to reset his
# password. Inside this email, there are some instructions about how
# to properly reset the password and an url pointing to the edit method.
# In the edit page the user will be able to change his password.
class PasswordResetsController < ApplicationController
  ##
  # The _create_ method. It's called when the user submitted the password
  # reset form. If everything is fine, it will send an email to the given
  # account with instructions inside on how to change his password and a link
  # pointing to the edit method.
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => _('Email sent with password reset instructions.')
  end

  ##
  # The _edit_ method. It handles the logic behind the form for changing
  # the password.
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  ##
  # The _update_ method. It's called when the user has submitted the edit
  # form. This method does the actual password resetting and finally
  # it redirects to the root url.
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_url, :alert => _('Password reset has expired.')
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => _('Password has been reset!')
    else
      render :edit
    end
  end

  ##
  # This method is called when the user is changing his password via
  # the account page.
  def auth_change
    if current_user && current_user.authenticate(params[:old_password])
      if current_user.update_attributes(params[:user])
        redirect_to account_url, :notice => 'Password updated successfully.'
      else
        redirect_to account_url, :alert => 'The password and its confirmation do not match.'
      end
    else
      redirect_to account_url, :alert => 'Dude, the old password you submitted is wrong.'
    end
  end
end

app/views/password_resets/edit.html.erb
<div class="pbucket">
  <%= form_for @user, url: password_reset_url(params[:id]) do |f| %>
    <div class="pbucket_title">
      <h1>Reset your password</h1>
      <span> Apparently, you've forgotten your password.</span>
      <br>
      <span>You can reset it by applying to this form.</span>
      <% if @user.errors.any? %>
        <div class="error_messages pbucket_errors">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="pbucket_body">
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, { class: 'r_raw_field' } %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, { class: 'r_raw_field' } %>
      </div>
      <%= r_submit _('Update Password'), 'r_submit' %>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_url, :method => :post, :id => 'reset_dialog' do %>
  <div class="header">
    <span>Reset your password</span>
  </div>
  <div class="dialog_body">
    <span>
      Apparently you don't remember your password. Say it ain't so! Anyway,
      if you submit this form we'll send you an email with instructions on
      how to reset your password.
    </span>
    <div class="holding span_trick" data-fieldname="email">
      <span class="holder">Email</span>
      <%= r_submit "Reset Password" %>
      <%= text_field_tag :email, nil, { class: 'r_raw_field'  } %>
    </div>
  </div>
<% end %> 