config/routes.rb
Rem::Application.routes.draw do
  # RESTful resources
  resources :password_resets, :places, :sessions
  resources :users, :except => [:show] # Rest API
  resources :routes, :except => [:show, :edit]
  resources :relationships, :only => [:create, :destroy]
  resources :route_relationships, :only => [:create, :destroy]

  # Users, sessions and accounts
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post '/search' => 'sessions#search', as: 'search'
  get 'signup' => 'users#new', as: 'signup'
  get 'ajax_request' => 'users#ajax_request', as: 'ajax_request'
  get 'account' => 'account#edit', as: 'account'
  put 'account' => 'account#update'
  get '/places/id/:id' => 'places#edit', as: 'map_place'

  post '/ajax/update_places' => 'routes#update_places'

  post '/change_password' => 'password_resets#auth_change', as: 'auth_change'

  # Rest API: Android login
  post '/android' => 'sessions#android'

  # Rest API: Show info about users, routes and places.
  get "/users/:name" => "users#show"
  get "/routes/:name" => "routes#show"
  get "/places/:name" => "places#show"

  # Rest API: Upload/remove photos.
  post "/photos/:route_id" => "places#photos"
  delete "/photos/:place_id" => "places#delete_photos"

  # Rest API: Show the routes of the given user
  get "/users/:name/routes" => "users#routes", as: 'user_routes'

  # Rest API: Get nearby locations
  get "/places/nearby/:id" => "places#nearby"

  # Following / followers
  get '/:name/:id/followers' => 'routes#followers', as: 'followers_route'
  get '/:name/following' => "users#following", as: 'following_user'
  get '/:name/followers' => "users#followers", as: 'followers_user'

  # OAuth paths
  controller :sessions do
    scope '/auth', as: 'auth' do
      match ':provider/callback' => :create
      match :failure
    end
  end

  # Home, sweet home :)
  root to: 'home#index'

  # Footer pages
  get '/about' => "home#about"
  get '/overview' => "home#overview"
  get '/contact' => "home#contact"
  get '/help' => "home#help"

  # API page
  resources :api, :only => [:index] do
    collection do
      get 'basics' => 'api#basics'
      get 'routes_places' => 'api#routes_places'
      get 'nearby' => 'api#nearby'
    end
  end

  # This is quite ugly though
  get "/:name/:route_id" => "routes#edit", as: 'edit_route', route_id: /\d+/

  # This is the last to be routed so we don't mess things up.
  get '/:name' => "users#edit"
end

app/models/user.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == User Class Definition
#
# This is the User model.
class User < ActiveRecord::Base
  # These are the attributes ready for mass-assignment.
  attr_accessible :name, :email, :password, :password_confirmation,
                  :full_name, :twitter_name, :location, :url

  # Let's make some validations.
  validates_uniqueness_of :name, :email
  validates_presence_of :name, :on => :create
  validates_presence_of :email, :password, :password_confirmation,
                        :password_digest, on: :create, :if => :is_rem?
  validates_with UserValidator, :on => :create

  # A user has many ways to authenticate: via rem account or
  # via external services (Twitter, Google/OpenID).
  has_many :authentications, dependent: :destroy

  # A user has many routes and it may follow routes from other people.
  has_many :routes, dependent: :destroy
  has_many :route_following, through: :route_relationships, source: :followed
  has_many :route_relationships, foreign_key: 'follower_id', dependent: :destroy

  # A user may follow/be-followed-by other users.
  has_many :following, through: :relationships, source: :followed
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy

  has_many :activities, dependent: :destroy

  # Rails 3.1 goodie :)
  has_secure_password

  # Perform some actions before creating/validating a user.
  before_create { generate_token(:auth_token) }
  before_validation :password_required?

  # We want Gravatar support :)
  include Gravtastic
  gravtastic secure: true, default: 'http://mssola.heroku.com/assets/rem_user.png'

  ##
  # Authentication with OmniAuth and sending password resets

  ##
  # Create a brand new user from an external service.
  #
  # @param *Hash* auth This is a hash with important info related to
  # this new user. It follows the OAuth format.
  def self.create_with_omniauth(auth)
    info = auth['info']
    urls = cleanup_urls(info['urls'])
    create! do |user|
      user.name = info['nickname']
      user.name ||= info['name'] + rand(1000).to_s
      user.email = info['email']
      user.full_name = info['name']
      user.location = info['location']
      user.url = urls[:site]
      user.twitter_name = urls[:twitter]
      user.authentications.build(provider: auth['provider'], uid: auth['uid'])
    end
  end

  ##
  # This method uses the UserMailer in order to send a
  # password reset mail.
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  ##
  # Handling the following/followed functionality

  ##
  # Return true if this user is following the given user/route.
  #
  # @param *User/Route* followed The user/route that we may be following.
  def following?(followed)
    if followed.class.to_s == 'Route'
      route_relationships.find_by_followed_id(followed)
    else
      relationships.find_by_followed_id(followed)
    end
  end

  ##
  # Return true if this user is following the given user and the given
  # user is the following this user.
  #
  # @param *User* followed The user/route that we may be following.
  def bi_following?(followed)
    self.following?(followed) && followed.following?(self)
  end

  # Include the create_activity! helper method
  include RemActivities

  ##
  # Follow the given user/route.
  #
  # @param *User/Route* followed The user/route we want to follow.
  def follow!(followed)
    bool = true
    if followed.class.to_s == 'Route'
      route_relationships.create! followed_id: followed.id
    else
      relationships.create! followed_id: followed.id
      bool = (self.id != followed.id)
    end
    create_activity! followed, 'followed', self.id if bool
  end

  ##
  # Unfollow the given user/route.
  #
  # @param *User/Route* followed We don't want to follow this
  # user/route anymore.
  def unfollow!(followed)
    bool = true
    if followed.class.to_s == 'Route'
      route_relationships.find_by_followed_id(followed).destroy
    else
      relationships.find_by_followed_id(followed).destroy
      bool = (self.id != followed.id)
    end
    create_activity! followed, 'unfollowed', self.id if bool
  end

  ##
  # Overriding to_xml and as_json to indicate what should be
  # shown from a user.

  ##
  # Override the as_json method to limit the fields returned.
  #
  # @param *Hash* options Options passed to this method. Unused.
  def as_json(options = {})
    options ||= { except: private_columns }
    super(options)
  end

  ##
  # The same as the _routes_ method but showing only the public ones
  # (thus, when protected = false).
  #
  # @return *Array* of all the public routes.
  def public_routes
    Route.where("user_id = ? AND protected = ?", self[:id], false)
  end

  private

  ##
  # Returns the most sensitive columns in this model
  def private_columns #:doc:
    [:updated_at, :password_digest, :password_reset_token,
     :password_reset_sent_at, :auth_token, :email]
  end

  ##
  # Generate an authorization token and assign it to the specified column.
  #
  # @param *Symbol* column The column where we'll store the generated token.
  def generate_token(column) #:doc:
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  ##
  # Is this a rem account signup ?
  #
  # @return *Boolean* True if this is a rem account, false otherwise.
  def is_rem? #:doc:
    return true if self.authentications.nil? || self.authentications.empty?
    self.authentications.each do |auth|
      return true if auth.provider == ""
    end
    false
  end

  ##
  # If the password is not required, tell the password_digest attribute
  # to shut up. Do nothing if this is a Rem account, so this digest
  # attribute can properly complain.
  def password_required? #:doc:
    unless authentications.empty? || !password.blank?
      self.password_digest = 0
    end
  end

  ##
  # Prepare a hash with the urls stripped for the user.
  #
  # @param *Hash* urls The urls given by the external service.
  #
  # @return *Hash* An empty hash if no urls is given at all. Otherwise
  # it will return a two-sized hash with the :site and :twitter keys.
  def self.cleanup_urls(urls) #:doc:
    return {} if urls.nil?
    urls['Twitter'].match /com\/(.+)$/
    { :site => urls['Website'], :twitter => $1 }
  end
end

app/controllers/users_controller.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == UsersController Class Definition
#
# The controller for the users. It can create new users through the Sign Up
# form. It can edit users through de dashboard and show users through the
# Rest API. A user can also delete his account so this controller must
# handle the destroy method too.
class UsersController < ApplicationController
  # This class responds to Ajax requests.
  include Hermes::AjaxRequest

  ##
  # The _new_ method. It corresponds to the signup page. It initializes
  # an empty user.
  def new
    @user = User.new
    @name, @email = params[:name], params[:email]
  end

  ##
  # The _create_ method. This method is called when a user has submitted
  # on the signup page. It creates this new user with the given parameters
  # available on the signup form. If everything is fine, it redirects the
  # user to his home page.
  def create
    @user = User.new(params[:user])
    if @user.save
      if params[:remember_me]
        cookies.permanent[:auth_token] = @user.auth_token
      else
        cookies[:auth_token] = @user.auth_token
      end
      redirect_to root_url, :notice => _('Signed up!')
    else
      render 'new'
    end
  end

  ##
  # The _edit_ method. This method corresponds to the user's dashboard.
  def edit
    @user = User.find_by_name!(params[:name])

    if current_user.nil?
      @routes = @user.public_routes
    elsif ((current_user.id != @user.id) && !(@user.bi_following?(current_user)))
      @routes = @user.public_routes
    else
      @routes = @user.routes
    end
    @activities = @user.activities.sort { |a, b| b.created_at <=> a.created_at }
  end

  ##
  # *Rest API*
  #
  # Shows the info about the user specified on the params variable
  # and can be accessed through /users/:name. It will return an XML if
  # the url specifies it, otherwise it will return a JSON object.
  def show
    @user = User.find_by_name(params[:name])
    raise ActionController::RoutingError.new('Not Found') if @user.nil?
    respond_to { |f| f.json { render :json => @user.to_json } }
  end

  ##
  # The _destroy_ method. This method is called when the user decided to
  # delete his account. At this point, this method will destroy the
  # user on our database and delete the auth_token on the cookies.
  def destroy
    @user = User.find(params[:id])
    destroy_activity! @user
    @user.destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => _('Account deleted')
  end

  ##
  # Show the users and routes this user is following.
  def following
    @shown = 'Following'
    @user = User.find_by_name(params[:name])
    @users = @user.following
    @routes = get_routes()
    render 'show_follow'
  end

  ##
  # Show this user's followers.
  def followers
    @shown = 'Followers'
    @user = User.find_by_name(params[:name])
    @users = @user.followers
    render 'show_follow'
  end

  ##
  # *Rest API*
  #
  # Show all the routes that the user with the name passed via params
  # actually has.
  def routes
    @user = User.find_by_name(params[:name])
    if android_user
      mroutes = @user.routes
    else
      mroutes = @user.public_routes
      if (current_user.nil? || (current_user.id != @user.id) && !(@user.bi_following?(current_user)))
        @routes = @user.public_routes
      else
        @routes = @user.routes
      end
    end
    respond_to do |format|
      format.json { render :json => mroutes.to_json }
      format.html { render 'show_routes' }
    end
  end

  private

  ##
  # Get the routes that can be displayed this user is following according
  # to our privacity policies.
  #
  # @return *Array* a two-sized array that has the route as its first element
  # and the owner's name as its last element.
  def get_routes #:doc:
    if current_user.nil? || current_user.id != @user.id
      return @user.route_following.map do |x|
        x if x.protected == false
      end.compact
    else
      res = @user.route_following
    end
  end
end

app/views/users/_follow.html.erb
<% if defined? user %>
  <% unless user.nil? %>
    <% @user = user %>
  <% end %>
<% end %>

<%= form_for current_user.relationships.build(:followed_id => @user.id) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow", class: 'r_follow' %></div>
<% end %>

app/views/users/_head.html.erb
<div id="user_head">
  <div class="avatar">
    <span class="tip" title="Change your avatar at gravatar.com">
      <a href="http://gravatar.com/emails/">
        <%= get_avatar_of @user, 48 %>
      </a>
    </span>
    <span id="user_nickname"><%= @user.name %></span>
    <% unless @user.full_name.nil? %>
      <span id="user_name"><%= "(#{@user.full_name})" %></span>
    <% end %>
    <% unless current_user.nil? %>
      <% unless current_user?(@user) %>
        <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= render partial: 'unfollow' %>
        <% else %>
          <%= render partial: 'follow' %>
        <% end %>
        </div>
      <% end %>
    <% end %>
      <div class="stretch"></div>
  </div>
</div>

app/views/users/_info.html.erb
<% present @user do |u| %>
  <div id="user_info">
    <div id="triumviri">
      <div id="personal_info">
        <% unless u.full_name.nil? %>
          <dl><dt>Full name</dt><dd><%= u.full_name %></dd></dl>
        <% end %>
        <% if !u.location.nil? && !u.location.empty? %>
          <dl><dt>Location</dt><dd><%= u.location %></dd></dl>
        <% end %>
        <% unless u.website.nil? %>
          <dl><dt>Website</dt><dd><%= u.website %></dd></dl>
        <% end %>
        <% unless u.twitter.nil? %>
          <dl><dt>Twitter</dt><dd><%= u.twitter %></dd></dl>
        <% end %>
        <dl><dt>Member Since</dt><dd><%= u.member_since %></dd></dl>
      </div>
      <div id="bio_yogurt">
<!--         Let there be the Bio -->
      </div>
      <div id="stats_info">
        <ul class="stats" >
          <li>
            <% n_routes = @user.routes.count %>
            <%= link_to n_routes, user_routes_url(@user.name) %>
            <span>routes</span>
          </li>
          <li>
            <% m_followers = @user.followers.count %>
            <%= link_to m_followers, followers_user_url(@user.name) %>
            <span>followers</span>
          </li>
        </ul>
        <div class="following_stats">
          <% m_foll = @user.following %>
          <div id="following">
          <b>
          Following <%= m_foll.count %> users and
          <% if current_user.nil? || (current_user.id != @user.id) %>
            <% fing = @user.route_following.select { |x| x.protected == false } %>
          <% else %>
            <% fing = @user.route_following %>
          <% end %>
          <%= pluralize(fing.count, 'route') %>
          </b>
          <%= link_to 'view all &rarr;'.html_safe, following_user_url(@user.name) %>
          </div>
          <ul id="following_avatars">
            <% m_foll.slice(0...10).each do |f| %>
              <li class="avatar">
                <span class="tip" title=<%= f.name %>>
                  <a href=<%= "/#{f.name}" %>>
                    <%= get_avatar_of f, 24 %>
                  </a>
                </span>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="stretch"></div>
  </div>
<% end %> 

app/views/users/_unfollow.html.erb
<% if defined? user %>
  <% unless user.nil? %>
    <% @user = user %>
  <% end %>
<% end %>

<%= form_for current_user.relationships.find_by_followed_id(@user),
                :method => :delete do |f| %>
  <div class="actions"><%= f.submit "Unfollow", class: 'r_submit' %></div>
<% end %> 

app/views/users/_user.html.erb
<div class="user">
  <div class="avatar"><a href=<%="/#{user.name}"%>>
    <%= get_avatar_of user, 20 %>
  </a></div>
  <%= link_to "#{user.name}", "/#{user.name}" %>
  <% if !user.full_name.nil? %>
    <span><%= "(#{user.full_name})" %></span>
  <% end %>
  <% if !current_user.nil? && !current_user?(user) %>
    <div id="follow_form">
      <% if current_user.following?(user) %>
        <%= render template: 'users/_unfollow', locals: { user: user } %>
      <% else %>
        <%= render template: 'users/_follow', locals: { user: user } %>
      <% end %>
    </div>
  <% end %>
  <div class="stretch"></div>
</div>

app/views/users/ajax_request.js.erb
<% if @ajax_response[:dest] ==  'existing_name' %>
  $('#existing_name').html("<%= escape_javascript(@ajax_response[:value]) %>");
<% end %>
<% if @ajax_response[:dest] == 'email_error' %>
  $('#email_error').html("<%= escape_javascript(@ajax_response[:value]) %>");
<% end %>

app/views/users/edit.html.erb
<% if @user.name.end_with? 's' %>
  <% title "#{@user.name}' Profile" %>
<% else %>
  <% title "#{@user.name}'s Profile" %>
<% end %>

<%= render partial: 'head' %>
<%= render partial: 'info' %>

<div id="user_body">
  <div id="user_routes" class="home_filter">
    <%= render partial: 'widgets/routes_filter', locals: { routes: @routes } %>
  </div>
  <div id="user_activity">
    <span>Public activity</span>
    <br><br>
    <div id="activity_list">
      <%= render @activities %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% title 'Sign Up' %>

<%= form_for @user do |f| %>
  <div class="signup">
    <h1>What are you waiting for?
    <br>
    <em class="join_rem">Join Rem.</em></h1>
    <div class="actions" id="user_submit"><%= r_submit 'Sign up!', 'r_signup' %>
    </div>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <fieldset class="textbox">
    <div class="prompt name">
      <div class="holding span_trick" data-fieldname="name">
        <div class="side_tip" id="existing_name">
        </div>
        <span class="holder">Username</span>
        <%= f.text_field :name, { class: 'r_raw_field', value: @name } %>
      </div>
    </div>
    <div class="prompt email">
      <div class="holding span_trick" data-fieldname="email">
        <div class="side_tip" id="email_error">
        </div>
        <span class="holder">Email</span>
        <%= f.text_field :email, { class: 'r_raw_field', value: @email } %>
      </div>
    </div>
    <div class="prompt password">
      <div class="holding span_trick" data-fieldname="password">
        <span class="holder">Password</span>
        <%= f.password_field :password, { class: 'r_raw_field' } %>
      </div>
    </div>
    <div class="prompt password_confirmation" >
      <div class="holding span_trick" data-fieldname="password_confirmation">
        <div class="side_tip" id="password_error">
        </div>
        <span class="holder">Confirm Password</span>
        <%= f.password_field :password_confirmation, { class: 'r_raw_field' } %>
        </div>
      </div>
      <%= r_check :remember_me %>
      <%= r_label :remember_label, 'Keep me logged-in on this computer.' %>
    </div>
  </fieldset>
<% end %>

app/views/users/show_follow.html.erb
<%= render partial: 'head' %>

<span class="user_title"><%= @shown %></span>

<br><br>

<% if @shown == 'Followers' %>
  <% unless @users.empty? %>
    <%= render @users %>
  <% end %>
<% else %>
  <% original = @user %>

  <div class="show_following">
    <div class="following_users">
      <% if current_user.nil? || !current_user?(@user) %>
        <span class="subtitle"><%= @user.name %> is following</span>
      <% else %>
        <span class="subtitle">You're following</span>
      <% end %>
      <br><br>
      <% unless @users.empty? %>
        <%= render @users %>
      <% end %>
    </div>
    <div class="following_routes">
      <% if current_user.nil? || !current_user?(original) %>
        <span class="subtitle"><%= original.name %> is watching</span>
      <% else %>
        <span class="subtitle">Your watched routes</span>
      <% end %>
      <br><br>
      <% unless @routes.empty? %>
        <% @routes.each do |r| %>
          <a href=<%= "/#{r.user.name}/#{r.id}" %>><%= r.user.name %>/<b><%= r.name %></b></a>
          <div class="stretch"></div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show_routes.html.erb
<% if @user.name.end_with? 's' %>
  <% title "#{@user.name}' routes" %>
<% else %>
  <% title "#{@user.name}'s routes" %>
<% end %>


<%= render partial: 'head' %>

<div class="show_routes_page">
  <% t = '' %>
  <% if current_user.id != @user.id && !@user.bi_following?(current_user) %>
    <span class="warning">You can't see its protected routes</span>
    <br>
  <% end %>

  <% if @user.id == current_user.id %>
    <span class="route_title">Your routes <%= t %></span>
  <% else %>
    <span class="route_title"><%= @user.name %>'s routes <%= t %></span>
  <% end %>

  <div id="routes_list">
    <% @routes.each do |r| %>
      <div class="user_route">
        <%= render r %>
      </div>
    <% end %>
  </div>
</div>