config/routes.rb
Rem::Application.routes.draw do
  # RESTful resources
  resources :password_resets, :places, :sessions
  resources :users, :except => [:show] # Rest API
  resources :routes, :except => [:show, :edit]
  resources :relationships, :only => [:create, :destroy]
  resources :route_relationships, :only => [:create, :destroy]

  # Users, sessions and accounts
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post '/search' => 'sessions#search', as: 'search'
  get 'signup' => 'users#new', as: 'signup'
  get 'ajax_request' => 'users#ajax_request', as: 'ajax_request'
  get 'account' => 'account#edit', as: 'account'
  put 'account' => 'account#update'
  get '/places/id/:id' => 'places#edit', as: 'map_place'

  post '/ajax/update_places' => 'routes#update_places'

  post '/change_password' => 'password_resets#auth_change', as: 'auth_change'

  # Rest API: Android login
  post '/android' => 'sessions#android'

  # Rest API: Show info about users, routes and places.
  get "/users/:name" => "users#show"
  get "/routes/:name" => "routes#show"
  get "/places/:name" => "places#show"

  # Rest API: Upload/remove photos.
  post "/photos/:route_id" => "places#photos"
  delete "/photos/:place_id" => "places#delete_photos"

  # Rest API: Show the routes of the given user
  get "/users/:name/routes" => "users#routes", as: 'user_routes'

  # Rest API: Get nearby locations
  get "/places/nearby/:id" => "places#nearby"

  # Following / followers
  get '/:name/:id/followers' => 'routes#followers', as: 'followers_route'
  get '/:name/following' => "users#following", as: 'following_user'
  get '/:name/followers' => "users#followers", as: 'followers_user'

  # OAuth paths
  controller :sessions do
    scope '/auth', as: 'auth' do
      match ':provider/callback' => :create
      match :failure
    end
  end

  # Home, sweet home :)
  root to: 'home#index'

  # Footer pages
  get '/about' => "home#about"
  get '/overview' => "home#overview"
  get '/contact' => "home#contact"
  get '/help' => "home#help"

  # API page
  resources :api, :only => [:index] do
    collection do
      get 'basics' => 'api#basics'
      get 'routes_places' => 'api#routes_places'
      get 'nearby' => 'api#nearby'
    end
  end

  # This is quite ugly though
  get "/:name/:route_id" => "routes#edit", as: 'edit_route', route_id: /\d+/

  # This is the last to be routed so we don't mess things up.
  get '/:name' => "users#edit"
end

app/models/route.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == Route Class Definition
#
# This is the model that represents a route. It belongs to
# a user and may have multiple places.
class Route < ActiveRecord::Base
  # Let's play with mass-assignment.
  attr_accessible :name, :user_id, :desc, :protected, :rating

  # Getting some validations done.
  validates_presence_of :name, :user_id, :on => :create
  validates_uniqueness_of :name, :scope => :user_id
  validates_length_of :desc, :maximum => 160

  # The basic definition of a route is: something that belongs to a user
  # and represents a set of places.
  belongs_to :user
  has_many :places, dependent: :destroy

  # A route may be followed by a certain number of users.
  has_many :followers, through: :reverse_route_relationships, source: :follower
  has_many :reverse_route_relationships, foreign_key: 'followed_id',
                                         class_name: 'RouteRelationship',
                                         dependent: :destroy

  ##
  # Override the as_json method to limit the fields returned.
  #
  # @param *Hash* options Options passed to this method. Unused.
  def as_json(options = {})
    options ||= { except: [:updated_at], include: :places }
    super(options)
  end
end

app/controllers/routes_controller.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == RoutesController Class Definition
#
# The controller for the routes. It allows us to create/edit/destroy routes
# and in the future it will bring some API methods.
class RoutesController < ApplicationController
  ##
  # The _new_ method. Initializes a new empty route.
  def new
    @route = Route.new
  end

  ##
  # *Rest API*
  #
  # The _create_ method. It creates a new route according to the params.
  def create
    name = params[:name].nil? ? params[:route] : { :name => params[:name] }
    @route = Route.new(name)

    current_user || android_user
    @route.user_id = @current_user.id unless @route.nil? || @current_user.nil?

    if !@current_user.nil? && @route.save
      @route.rating = 0
      create_activity! @route, 'created'
      @current_user.follow! @route
      respond_to do |format|
        format.json { render :json => rem_created(@route), status: 201 }
        format.html { redirect_to edit_route_url(@current_user.name, @route.id) }
      end
    else
      msg = @route.errors.messages
      if !msg.empty? && msg[:name].first == 'has already been taken'
        error = 409
      else
        error = @current_user.nil? ? 401 : 404
      end

      respond_to do |format|
        format.json { render :json => rem_error(error), :status => error }
        format.html { render 'new' }
      end
    end
  end

  ##
  # The _edit_ method. It edits an existing route identified by the id
  # passed via params of the user identified by the name passed via params.
  def edit
    @user = User.find_by_name(params[:name])
    @route = @user.routes.find(params[:route_id])
    @places = @route.places.sort do |a, b|
      # Sort handling nil values
      (a.index && b.index ) ? a.index <=> b.index : ( a.index ? -1 : 1 )
    end
    @places.each { |p| puts p.name }
    @markers = @places.to_gmaps4rails
  end

  ##
  # The _update_ method. Can be called for the json format when best_in_place
  # is requesting it. Otherwise, the response format will be html.
  def update
    @route = Route.find(params[:id])

    respond_to do |format|
      if @route.update_attributes(params[:route])
        format.html { redirect_to map_place_url, :notice => 'Route updated successfully' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @route.errors.full_messages, :status => :unprocessable_entity }
      end
    end
  end

  ##
  # *Rest API*
  #
  # Shows the info about the route specified on the params variable
  # and can be accessed through /routes/:name. It will return an XML if
  # the url specifies it, otherwise it will return a JSON object.
  def show
    route = Route.find_by_name(params[:name])
    raise ActionController::RoutingError.new('Not Found') if route.nil?

    if route.protected and android_user.nil?
      respond_to { |f| f.json { render :json => rem_error(401), status: 401 } }
    else
      respond_to { |f| f.json { render :json => route.to_json } }
    end
  end

  ##
  # *Rest API*
  #
  # The _destroy_ method. It deletes all the info about a route and
  # redirects the user to the home page.
  def destroy
    begin
      route = Route.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error_occurred 404
      return nil
    end

    current_user || android_user
    if @current_user.nil?
      error_occurred 401
    elsif route.user_id != @current_user.id
      error_occurred 409
    else
      destroy_activity! route
      route.destroy
      respond_to do |format|
        format.json { render json: { 'msg' => 'Route destroyed', status: 200 }}
        format.html { redirect_to root_url, :notice => 'Route destroyed' }
      end
    end
  end

  ##
  # Show the followers for this route and redirect to the show_follow page.
  def followers
    @user = User.find_by_name(params[:name])
    @route = @user.routes.find(params[:id])
    @followers = @route.followers
    render 'show_follow'
  end

  ##
  # Update the index of the places of the currently shown route. This is
  # a method called via AJAX, so the response follows the JSON format.
  def update_places
    params['res'].each_with_index do |i, j|
      place = Place.find(i.to_i)
      unless place.update_attribute('index',  j)
        respond_to { |f| f.json { head 404 } }
      end
    end
    respond_to { |f| f.json { head :ok } }
  end
end

app/views/routes/_action_buttons.html.erb
<div id="action_container">
  <div id="action_nav"><a href="#" class="acting"><span>More actions</span></a></div>
  <fieldset id="action_menu">
    <%= button_to 'Add places', new_place_url, method: :get, class: "action_button" %>
    <%= button_to 'Delete Route', route_url(@route.id), method: :delete, class: "action_button" %>
  </fieldset>
</div>

app/views/routes/_follow.html.erb
<%= form_for current_user.route_relationships.build(:followed_id => @route.id) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow", class: 'r_follow' %></div>
<% end %> 

app/views/routes/_route.html.erb
<% if route.protected %>
<li class="protected route">
<% else %>
<li class="public route">
<% end %>
  <%= link_to "#{route.name}", "/#{route.user.name}/#{route.id}", :class => 'route_name' %>
  <ul class="route-stats">
    <% if route.protected %>
      <li class="protected_watchers" title="Watchers">
    <% else %>
      <li class="watchers" title="Watchers">
    <% end %>
      <%= link_to route.followers.count, followers_route_url(route.user.name, route.id) %>
    </li>
  </ul>
  <% if defined? home %>
    <br><br>
  <% else %>
    <div class="route_body">
      <% if route.desc.nil? || route.desc.empty? %>
        <p>No description was given.</p>
      <% else %>
        <p><%= route.desc %></p>
      <% end %>
    </div>
  <% end %>
</li>

app/views/routes/_unfollow.html.erb
<%= form_for @user.route_relationships.find_by_followed_id(@route), :method => :delete do |f| %>
  <div class="actions">
    <%= f.submit "Unfollow", class: 'r_submit' %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<% content_for(:head) do %>
  <%= javascript_tag "var remMarkers = #{@markers.to_json};" %>
<% end %>

<% if current_user.nil? || (current_user.id != @user.id) %>
  <% cond = false %>
<% else %>
  <% cond = (current_user.id == @route.user_id) %>
<% end %>

<div id="road_map"></div>

<% if cond %>
  <%= render :partial => 'action_buttons' %>
<% end %>

<div class="route_rdock">
  <div class="route_ibucket">
    <ul class="route_bucket_title">
      <li class="prompt name">
	<% if cond %>
	  <%= label_tag :name_label, _('Name'), title: 'Click contents to edit', class: 'r_label stip' %>:
	<% else %>
	  <%= label_tag :name_label, _('Name'), class: 'r_label' %>:
	<% end %>
	<%= best_in_place_if cond, @route, :name, :inner_class => 'r_raw_field' %>
      </li>
      <li class="prompt desc">
	<% if cond %>
	  <%= label_tag :desc_label, _('Description'), title: 'Click contents to edit', class: 'r_label tip' %>:
	<% else %>
	  <%= label_tag :desc_label, _('Description'), class: 'r_label' %>:
	<% end %>
	<%= best_in_place_if cond, @route, :desc, :type => :textarea, :inner_class => 'r_text_area', nil: 'Click me to add content!' %>
      </li>
    </ul>
  </div>

  <div class="route_idock">
    <% if cond %>
      <% unless @places.empty? %>
        <span class="idock_desc">
          Drag & Drop the items on the list below to change the order you want
        </span>
        <span class="idock_desc">the places to have in this route.</span>
      <% else %>
        <span class="idock_desc">
          This route is empty! Please add new places by clicking on the
        </span>
        <span class="idock_desc">
          'More actions' button above and then selecting 'Add places'.
        </span>
      <% end %>
    <% end %>
    <div class="idock_info" hidden="true">
      <span class="idock_title"></span>
      <a href="">go &rarr;</a>
      <br>
      <span class="img_base" hidden="true"><%= "/assets/#{@route.user_id}/#{@route.id}/" %></span>
      <img src="" width="132"></img>
    </div>
    <ul id="places_sortable">
      <% @places.each do |p| %>
	<li class="<%= "ui-state-default #{p.id}" %>"><%= p.name %></li>
      <% end %>
    </ul>
  </div>

  <% if cond %>
    <div id="save_changes" hidden="true">
      <%= r_submit 'Save changes', nil %>
      <span></span>
    </div>
  <% elsif !current_user.nil? && (current_user.id != @user.id) %>
    <div class="follow_route_button">
      <% if current_user.following?(@route) %>
        <%= render :partial => 'unfollow' %>
      <% else %>
        <%= render :partial => 'follow' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/routes/new.html.erb
<% title 'New route' %>

<% if @route.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @route.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @route do |f| %>
  <div class="new_route_head">
    <span>Create a brand new route!</span>
  </div>
  <div class="new_route_body">
    <fieldset class="textbox">
      <div class="prompt name">
        <%= r_label :name_label, 'Route name' %>
        <%= f.text_field :name, { class: 'r_text_field' } %>
      </div>
      <div class="prompt desc">
        <%= r_label :desc_label, 'Description' %>
        <span id="desc_adv">
          (About this route in less than 160 chars.)
        </span>
        <%= f.text_area :desc, { class: 'r_text_area' } %>
      </div>
      <div class="protect_route">
        <%= f.check_box :protected %>
        <%= r_label :protected_label, 'Keep this route protected' %>
      </div>
      <% if current_user.nil? %>
        <%= r_submit 'Create route', nil, disabled: true %>
      <% else %>
        <%= r_submit 'Create route', nil %>
      <% end %>
    </fieldset>
  </div>
<% end %>

app/views/routes/show_follow.html.erb
<div id="route_head">
  <h3>Route:</h3>
  <span><%= @route.name %></span>
  <% if @route.user_id != current_user.id %>
    <div id="route_follow_form">
      <% if current_user.following?(@route) %>
        <%= render partial: 'unfollow' %>
      <% else %>
        <%= render partial: 'follow' %>
      <% end %>
    </div>
  <% end %>
  <div class="stretch"></div>
</div>

<% @route.followers.each do |u| %>
  <%= render u %>
  <div class="stretch"></div>
<% end %>