config/routes.rb
Rem::Application.routes.draw do
  # RESTful resources
  resources :password_resets, :places, :sessions
  resources :users, :except => [:show] # Rest API
  resources :routes, :except => [:show, :edit]
  resources :relationships, :only => [:create, :destroy]
  resources :route_relationships, :only => [:create, :destroy]

  # Users, sessions and accounts
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post '/search' => 'sessions#search', as: 'search'
  get 'signup' => 'users#new', as: 'signup'
  get 'ajax_request' => 'users#ajax_request', as: 'ajax_request'
  get 'account' => 'account#edit', as: 'account'
  put 'account' => 'account#update'
  get '/places/id/:id' => 'places#edit', as: 'map_place'

  post '/ajax/update_places' => 'routes#update_places'

  post '/change_password' => 'password_resets#auth_change', as: 'auth_change'

  # Rest API: Android login
  post '/android' => 'sessions#android'

  # Rest API: Show info about users, routes and places.
  get "/users/:name" => "users#show"
  get "/routes/:name" => "routes#show"
  get "/places/:name" => "places#show"

  # Rest API: Upload/remove photos.
  post "/photos/:route_id" => "places#photos"
  delete "/photos/:place_id" => "places#delete_photos"

  # Rest API: Show the routes of the given user
  get "/users/:name/routes" => "users#routes", as: 'user_routes'

  # Rest API: Get nearby locations
  get "/places/nearby/:id" => "places#nearby"

  # Following / followers
  get '/:name/:id/followers' => 'routes#followers', as: 'followers_route'
  get '/:name/following' => "users#following", as: 'following_user'
  get '/:name/followers' => "users#followers", as: 'followers_user'

  # OAuth paths
  controller :sessions do
    scope '/auth', as: 'auth' do
      match ':provider/callback' => :create
      match :failure
    end
  end

  # Home, sweet home :)
  root to: 'home#index'

  # Footer pages
  get '/about' => "home#about"
  get '/overview' => "home#overview"
  get '/contact' => "home#contact"
  get '/help' => "home#help"

  # API page
  resources :api, :only => [:index] do
    collection do
      get 'basics' => 'api#basics'
      get 'routes_places' => 'api#routes_places'
      get 'nearby' => 'api#nearby'
    end
  end

  # This is quite ugly though
  get "/:name/:route_id" => "routes#edit", as: 'edit_route', route_id: /\d+/

  # This is the last to be routed so we don't mess things up.
  get '/:name' => "users#edit"
end

app/helpers/layout_helper.rb
#
# Author:: Copyright (C) 2011  Miquel Sabaté (mikisabate@gmail.com)
#
# License::
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


##
# == LayoutHelper Module definition.
#
# Acts as a namespace for helper methods that set variables to
# be used in the layout.
module LayoutHelper
  # So we can use the Rem widgets all over our templates.
  include RemWidgets

  ##
  # Sets the title of the page.
  #
  # @param *String* page_title The title of the page.
  #
  # @param *Boolean* show_title True if the title should be
  # shown at the page body, false otherwise.
  def title(page_title, show_title = false)
    content_for(:title) { h(page_title) }
    @show_title = show_title
  end

  ##
  # Getter of the _show_title_ attribute.
  #
  # @return *Boolean* True if the title should be shown at
  # the page body, false otherwise.
  def show_title?
    @show_title
  end

  ##
  # Sets the stylesheet of the page. This is a wrapper of
  # the stylesheet_link_tag method..
  #
  # @param *Argument* *List* args The args to pass to the
  # stylesheet_link_tag method.
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  ##
  # Sets the javascript of the page. This is a wrapper of
  # the javascript_include_tag method.
  #
  # @param *Argument* *List* args The args to pass to the
  # javascript_include_tag method.
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end
 

app/views/layouts/_footer.html.erb
<div id="footer" >
  <div class="footer_stretch"></div>
  <div class="footer_dock">
    <div class="footer_title">Rem</div>
    <ul class="footer_nav">
      <li><a href="/about">About Rem</a>
      <li><a href="/contact">Contact & Support</a>
    </ul>
  </div>
  <div class="footer_dock">
    <div class="footer_title">Documentation</div>
    <ul class="footer_nav">
      <li><a href="/help">Help</a>
      <li><a href="/api">Developer API</a>
    </ul>
  </div>
</div> 

app/views/layouts/_login.html.erb
<div id="login_container">
  <div id="topnav" class="topnav"> Have an account? <a href="login" class="signin"><span>Sign in</span></a> </div>
  <fieldset id="signin_menu">
    <%= form_tag sessions_url do %>
      <p>
        <%= r_label :name_or_email, 'Username or email' %>
        <%= r_field :text, :name_or_email %>
      </p>
      <p>
        <%= r_label :password %>
        <%= r_field :password, :password %>
      </p>
      <%= link_to _('Forgotten password?'), new_password_reset_url,
      :title => 'Click here if you do not remeber your password' %>
      <p class="remember">
        <%= r_submit 'Log in' %>
        <%= r_check :remember_me %>
        <%= r_label :remember_me %>
      </p>
      <div id="logos" >
        <a href="/auth/twitter">
          <%= image_tag 'twitter_tiny.png', height: '20', class: 'tip', title: 'Log in with your Twitter account' %>
        </a>
        <a href="/auth/google">
          <%= image_tag 'google_tiny.png', height: '20', class: 'tip', title: 'Log in with your Google account' %>
        </a>
      </div>
    <% end %>
  </fieldset>
</div> 

app/views/layouts/_top.html.erb
<div id="top_bar">
  <div id="top_sep">
    <a href="/" id="rem">About Rem</a>
    <% if current_controller?('api') %>
      <ul id="api_top">
        <li><%= link_to 'API:', '/api' %></li>
        <li><%= link_to 'Basics', '/api/basics' %></li>
        <li><%= link_to 'Routes & Places', '/api/routes_places' %></li>
        <li><%= link_to 'Nearby locations', '/api/nearby' %></li>
      </ul>
    <% end %>
    <% if current_user %>
      <div id="top_right">
        <div class="avatar">
          <a href="/">
            <%= get_avatar_of current_user %>
          </a>
        </div>
        <ul id="hot_top">
          <li><%= link_to "#{current_user.name}", root_url %></li>
          <li><%= link_to 'Profile', "/#{current_user.name}" %></li>
          <li><%= link_to 'Account Settings', account_url %></li>
          <li><%= link_to 'Log out', logout_url %></li>
        </ul>
      </div>
        <div id="top_search" class="span_trick">
          <form accept-charset="UTF-8" action="/search" method="post">
            <span>Search&hellip;</span>
            <%= r_field :text, :search, 'r_raw_field' %>
          </form>
        </div>
    <% else %>
      <%= render :template => 'layouts/_login' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <link rel="icon" href="https://mssola.heroku.com/favicon.png" type="image/png" />
    <title>
      <%= content_for?(:title) ? "Rem / #{yield(:title)}" : 'Rem' %>
    </title>
    <%= stylesheet 'application' %>
    <%= javascript 'application' %>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render :template => 'layouts/_top' %>
    <div id="flash_container">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{key}", class: :flashy %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
    <%= render :template => 'layouts/_footer' %>
    <%= yield :scripts %>
  </body>
</html>